baseURL = "https://www.mith.pl/"
languageCode = "en-us"
title = "Make It Happen"
theme = "jel"
MetaDataFormat = "yaml"
sectionPagesMenu = "main"

[outputs]
    home = ["HTML"]
    page = ["HTML", "JSON"]

[permalinks]
page = "/:title/"
about = "/:filename/"
