backend:
  name: git-gateway
  branch: master
  
media_folder: static/images
public_folder: images

collections:
  - label: Products
    name: products
    folder: content/products
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: SEO_Title, name: seo_title, widget: string}
      - {label: SEO_Summary, name: seo_summary, widget: string}
      - {label: SEO_Keywords, name: seo_keywords, widget: string}
      - {label: Description, name: description, widget: string, required: false}
      - {label: Small_Description, name: small_description, widget: string, required: false}
      - {label: Thumbnail, name: thumbnail, widget: image, required: true}
      - {label: Content, name: content, widget: markdown}
      - label: Images
        name: images
        widget: list
        fields:
          - {label: Image, name: image, widget: image}
      - label: Booked_dates
        name: booked_dates
        required: false
        widget: list
        fields:
        - {label: Date, name: date, widget: date}
  - label: Gallery
    name: gallery
    folder: content/projects/gallery
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: SEO_Title, name: seo_title, widget: string}
      - {label: SEO_Summary, name: seo_summary, widget: string}
      - {label: SEO_Keywords, name: seo_keywords, widget: string}
      - {label: Thumbnail, name: thumbnail, widget: image, required: true}
      - label: Images
        name: images
        widget: list
        fields:
          - {label: Image, name: image, widget: image}
  - label: Category
    name: category
    folder: content/decors/category
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: SEO_Title, name: seo_title, widget: string}
      - {label: SEO_Summary, name: seo_summary, widget: string}
      - {label: SEO_Keywords, name: seo_keywords, widget: string}
      - {label: Description, name: description, widget: string, required: false}
      - {label: Small_Description, name: small_description, widget: string, required: false}
      - {label: Thumbnail, name: thumbnail, widget: image, required: true}
      - label: Products
        name: products
        widget: list
        fields:
          - label: Path
            name: path
            widget: relation
            collection: products
            searchFields: [description, title]
            valueField: title
  - name: data
    label: Data
    files:
      - label: Links&Navbar
        name: data
        file: content/data/_index.md
        create: false
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Mail, name: mail, widget: string, required: false}
          - {label: Phone_numbers, name: phone_numbers, widget: string, required: false}
          - {label: Facebook_url, name: facebook_url, widget: string, required: false}
          - {label: Instagram_url, name: instagram_url, widget: string, required: false}
          - {label: Pinterest_url, name: pinterest_url, widget: string, required: false}
          - {label: form_name, name: form_name, widget: string, required: false}
          - {label: form_name_prompt, name: form_name_prompt, widget: string, required: false}
          - {label: form_email, name: form_email, widget: string, required: false}
          - {label: form_email_prompt, name: form_email_prompt, widget: string, required: false}
          - {label: form_product, name: form_product, widget: string, required: false}
          - {label: form_product_prompt, name: form_product_prompt, widget: string, required: false}
          - {label: form_telephone, name: form_telephone, widget: string, required: false}
          - {label: form_telephone_prompt, name: form_telephone_prompt, widget: string, required: false}
          - {label: form_date, name: form_date, widget: string, required: false}
          - {label: form_count, name: form_count, widget: string, required: false}
          - {label: form_count_prompt, name: form_count_prompt, widget: string, required: false}
          - {label: form_question, name: form_question, widget: string, required: false}
          - {label: form_question_prompt, name: form_question_prompt, widget: string, required: false}
          - label: Navbar
            name: navbar
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Url, name: url, widget: string}
  - name: pages
    label: Pages
    files:
      - label: About page
        name: about
        file: content/about/_index.md
        create: true
        fields:
          - {label: Title, name: title, widget: string}
          - {label: SEO_Title, name: seo_title, widget: string}
          - {label: SEO_Summary, name: seo_summary, widget: string}
          - {label: SEO_Keywords, name: seo_keywords, widget: string}
          - {label: Description, name: description, widget: string, required: false}
          - {label: Small_Description, name: small_description, widget: string, required: false}
          - {label: Background_Image, name: image, widget: image, required: false}
          - {label: Add_Blend, name: blend, widget: boolean, required: false}
          - {label: First_image, name: first_thumbnail, widget: image}
          - {label: Second_Image, name: second_thumbnail, widget: image}
          - {label: Third_Image, name: third_thumbnail, widget: image}
          - {label: Content, name: content, widget: markdown}
          - {label: Right_Content, name: right_content, widget: markdown}
          - {label: Is_form, name: enable_form, widget: boolean}
      - label: Decors page
        name: decors
        file: content/decors/_index.md
        create: true
        fields:
          - {label: Title, name: title, widget: string}
          - {label: SEO_Title, name: seo_title, widget: string}
          - {label: SEO_Summary, name: seo_summary, widget: string}
          - {label: SEO_Keywords, name: seo_keywords, widget: string}
          - {label: Description, name: description, widget: string, required: false}
          - {label: Small_Description, name: small_description, widget: string, required: false}
          - {label: Background_Image, name: image, widget: image, required: false}
          - {label: Add_Blend, name: blend, widget: boolean, required: false}
          - {label: Is_form, name: enable_form, widget: boolean}
          - label: Categories
            name: category
            widget: list
            fields:
              - label: Category
                name: path
                widget: relation
                collection: category
                searchFields: [title, description]
                valueField: title
      - label: Projects page
        name: projects
        file: content/projects/_index.md
        create: true
        fields:
          - {label: Title, name: title, widget: string}
          - {label: SEO_Title, name: seo_title, widget: string}
          - {label: SEO_Summary, name: seo_summary, widget: string}
          - {label: SEO_Keywords, name: seo_keywords, widget: string}
          - {label: Description, name: description, widget: string, required: false}
          - {label: Small_Description, name: small_description, widget: string, required: false}
          - {label: Background_Image, name: image, widget: image, required: false}
          - {label: Add_Blend, name: blend, widget: boolean, required: false}
          - {label: Is_form, name: enable_form, widget: boolean}
          - label: Gallery
            name: gallery
            widget: list
            fields:
              - {label: Path, name: path, widget: relation, collection: gallery, searchFields: [title], valueField: title}
      - label: How page
        name: how
        file: content/how/_index.md
        create: true
        fields:
          - {label: Title, name: title, widget: string}
          - {label: SEO_Title, name: seo_title, widget: string}
          - {label: SEO_Summary, name: seo_summary, widget: string}
          - {label: SEO_Keywords, name: seo_keywords, widget: string}
          - {label: Description, name: description, widget: string, required: false}
          - {label: Small_Description, name: small_description, widget: string, required: false}
          - {label: Background_Image, name: image, widget: image, required: false}
          - {label: Add_Blend, name: blend, widget: boolean, required: false}
          - {label: Is_form, name: enable_form, widget: boolean}
          - label: Features
            name: features
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: markdown}
      - label: Home page
        name: home
        file: content/_index.md
        create: true
        fields:
          - {label: Title, name: title, widget: string}
          - {label: SEO_Title, name: seo_title, widget: string}
          - {label: SEO_Summary, name: seo_summary, widget: string}
          - {label: SEO_Keywords, name: seo_keywords, widget: string}
          - {label: About_image, name: about_image, widget: image}
          - {label: About_title, name: about_title, widget: string}
          - {label: About_description, name: about_description, widget: string}
          - {label: About_url, name: about_url, widget: string}
          - {label: Decors_title, name: decors_title, widget: string}
          - {label: Decors_description, name: decors_description, widget: string}
          - {label: Decors_complex_description, name: decors_complex_description, widget: text}
          - {label: Decors_url, name: decors_url, widget: string}
          - {label: Decors_image_first, name: decors_image_first, widget: image}
          - {label: Decors_title_first, name: decors_title_first, widget: string}
          - {label: Decors_url_first, name: decors_url_first, widget: string}
          - {label: Decors_image_second, name: decors_image_second, widget: image}
          - {label: Decors_title_second, name: decors_title_second, widget: string}
          - {label: Decors_url_second, name: decors_url_second, widget: string}
          - {label: Decors_image_third, name: decors_image_third, widget: image}
          - {label: Decors_title_third, name: decors_title_third, widget: string}
          - {label: Decors_url_third, name: decors_url_third, widget: string}
          - {label: Decors_image_fourth, name: decors_image_fourth, widget: image}
          - {label: Decors_title_fourth, name: decors_title_fourth, widget: string}
          - {label: Decors_url_fourth, name: decors_url_fourth, widget: string}
          - {label: How_title, name: how_title, widget: string}
          - {label: How_description, name: how_description, widget: string}
          - {label: How_complex_description, name: how_complex_description, widget: string}
          - {label: How_url, name: how_url, widget: string}
          - {label: How_image_first, name: how_image_first, widget: image}
          - {label: How_image_second, name: how_image_second, widget: image}
          - {label: How_image_third, name: how_image_third, widget: image}
          - {label: More_text, name: more_text, widget: string}
          - {label: Form_title, name: form_title, widget: string}
          - {label: Form_description, name: form_description, widget: string}
          - {label: Form_complex_description, name: form_complex_description, widget: text}
      - label: Form page
        name: form
        file: content/form/_index.md
        create: true
        fields:
          - {label: Title, name: title, widget: string}
          - {label: SEO_Title, name: seo_title, widget: string}
          - {label: SEO_Summary, name: seo_summary, widget: string}
          - {label: SEO_Keywords, name: seo_keywords, widget: string}
          - {label: Description, name: description, widget: string, required: false}
          - {label: Small_Description, name: small_description, widget: string, required: false}
          - {label: Background_Image, name: image, widget: image, required: false}
          - {label: Add_Blend, name: blend, widget: boolean, required: false}
          - {label: Content, name: content, widget: markdown}
          - {label: Is_form, name: enable_form, widget: boolean}
      - label: Privacy page
        name: privacy
        file: content/privacy/_index.md
        create: true
        fields:
          - {label: Title, name: title, widget: string}
          - {label: SEO_Title, name: seo_title, widget: string}
          - {label: SEO_Summary, name: seo_summary, widget: string}
          - {label: SEO_Keywords, name: seo_keywords, widget: string}
          - {label: Description, name: description, widget: string, required: false}
          - {label: Small_Description, name: small_description, widget: string, required: false}
          - {label: Background_Image, name: image, widget: image, required: false}
          - {label: Add_Blend, name: blend, widget: boolean, required: false}
          - {label: Content, name: content, widget: markdown}
          - {label: Is_form, name: enable_form, widget: boolean}

  